apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vlx17ytqt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vlx17ytqt-python 
  name: vlx17ytqt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vlx17ytqt-python 
